In [1]:
!pip install pandas praat-parselmouth tqdm

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting praat-parselmouth
  Downloading praat_parselmouth-0.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.9 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading praat_parselmouth-0.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (10.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 86.2 MB/s eta 0:00:00
Installing collected packages: praat-parselmouth
Successfully installed praat-parselmouth-0.4.7

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!unzip /content/drive/MyDrive/project/ru-fr_interference.zip -d /content/data

Streaming output truncated to the last 5000 lines.
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp58.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp14.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp20.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp30.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp16.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp47.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp75.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp35_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp22.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp12.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp36.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp51.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp67_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp19_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp7.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp10_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp2.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp66.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp53.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp74.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp32_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp71.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp28.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp32.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp73_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp32.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp36.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp47.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp77.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp73.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp49_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp13_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp46.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp44.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp42.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp48.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp17.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp39.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp5.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp47.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp40.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp42_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp48_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp71.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp77.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp26.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp77_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp31_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp13.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp2.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp53.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp40.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp19.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp46_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp8_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp25.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp39.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp52.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp40.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp51.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp21.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp76.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp54.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp39.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp26.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp70.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp75_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp43.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp45.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp7.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp15.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp68_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp64.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp1.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp19.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp48.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp52.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp34.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp18.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp10.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp60.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp52.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp41.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp70_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp68.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp50.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp47_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp57_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp22.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp62.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp36_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp50.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp43.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp12_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp78_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp61.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp63.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp54.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp57.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp17.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp37.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp41_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp63.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp25.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp58_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp17.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp69.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp68.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp12.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp25_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp18.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp55.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp50.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp62.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp41.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp45.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp74.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp56.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp8.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp56_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp33.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp40_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp15.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp70.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp60.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp35.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp76.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp64_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp23.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp38.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp69.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp30.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp67.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp42.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp35.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp71_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp77.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp10.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp24.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp19.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp73.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp1.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp44.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp58.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp3.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp5_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp73.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp61_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp52_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp37_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp37.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp28.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp49.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp75.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp11.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp23.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp78.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp21_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp13.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp66_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp59.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp1.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp1_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp28.wav
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp44_words.csv
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp66.txt
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp3.TextGrid
  inflating: /content/data/ru-fr_interference/2/wav_et_textgrids/FRcorp_textgrids_only/AN/an_fra_list1_FRcorp11.wav

delete everything before this cell below then save as .py file for dvc

In [49]:
import os
import pandas as pd
import parselmouth
from tqdm import tqdm

os.environ["DATA_DIR"] = "/content/data/ru-fr_interference/2"
BASE_DIR = os.getenv("DATA_DIR", "./data")
# Path to the folder that contains one folder per speaker
DATA_DIR = os.path.join(BASE_DIR, "wav_et_textgrids", "FRcorp_textgrids_only")
META_PATH = os.path.join(BASE_DIR, "metadata_RUFR.csv")
# Path where we save the final phoneme table
OUTPUT_PATH = os.path.join(BASE_DIR, "phoneme_table.csv")

# We store each phoneme token as one row in this list
rows = []

In [51]:
# Loop over speaker folders
for speaker_id in os.listdir(DATA_DIR):
    speaker_path = os.path.join(DATA_DIR, speaker_id)
    # Skip anything that is not a folder
    if not os.path.isdir(speaker_path):
        continue
    # Loop over files inside one speaker folder
    for file in os.listdir(speaker_path):
        # We only need TextGrid files here
        if not file.endswith(".TextGrid"):
            continue
        tg_path = os.path.join(speaker_path, file) # Full path to the TextGrid file
        wav_path = tg_path.replace(".TextGrid", ".wav") # The wav file should have the same name as the TextGrid file
        if not os.path.exists(wav_path):
            continue
        fname = file.replace(".TextGrid", "") # Remove the file extension and Split the filename into parts
        parts = fname.split("_")
        lang = parts[1] # parts[1] is the language group: fra or rus
        sentence_id = parts[-1] # The last part gives the sentence id
        L1 = "L1" if lang == "fra" else "L2"
        rep = parts[2] # repetition index e.g: list1
        rep_idx = int(rep.replace("list", ""))
        # Read the TextGrid as a normal text file
        with open(tg_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
        # We will collect only intervals from the phones tier
        in_phones_tier = False
        current_interval = {}
        phoneme_list = []

        for line in lines:
            line = line.strip()
            if line.startswith('name = "phones"'): # Detect the start of the phones tier
                in_phones_tier = True
                continue
            if in_phones_tier and line.startswith("item ["): # in case there are more than two tiers skip them
                break
            # Read interval information inside phones tier
            if in_phones_tier:
                if line.startswith("xmin ="):
                    current_interval["onset"] = float(line.split("=")[1].strip())
                elif line.startswith("xmax ="):
                    current_interval["offset"] = float(line.split("=")[1].strip())
                elif line.startswith("text ="):
                    label = line.split("=", 1)[1].strip().strip('"')
                    # Skip empty and silence intervals
                    if label not in ["", "sil", "sp", "spn"] and "..." not in label and len(label) <= 3:
                        current_interval["label"] = label
                        phoneme_list.append(current_interval.copy())
                    current_interval = {} # just to be safe, we reset
        # creating a list of all phonemes
        for p in phoneme_list:
            rows.append({
                "speaker_id": speaker_id,
                "sentence_id": sentence_id,
                "repetition": rep_idx,
                "filename": fname,
                "lang": lang,
                "L1": L1,
                "label": p["label"],
                "onset": p["onset"],
                "duration": p["offset"] - p["onset"],
                "offset": p["offset"],
                "wav_path": wav_path
            })

In [52]:
df = pd.DataFrame(rows)

In [53]:
df

,speaker_id,sentence_id,repetition,filename,lang,L1,label,onset,duration,offset,wav_path
0,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,d,0.45231,0.10769,0.56000,/content/data/ru-fr_interference/2/wav_et_text...
1,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,i,0.56000,0.18000,0.74000,/content/data/ru-fr_interference/2/wav_et_text...
2,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,s,0.74000,0.14000,0.88000,/content/data/ru-fr_interference/2/wav_et_text...
3,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,e,0.88000,0.12142,1.00142,/content/data/ru-fr_interference/2/wav_et_text...
4,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,ʁ,1.00142,0.07858,1.08000,/content/data/ru-fr_interference/2/wav_et_text...
...,...,...,...,...,...,...,...,...,...,...,...
45187,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,w,1.67000,0.03000,1.70000,/content/data/ru-fr_interference/2/wav_et_text...
45188,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,a,1.70000,0.06000,1.76000,/content/data/ru-fr_interference/2/wav_et_text...
45189,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,f,1.76000,0.12000,1.88000,/content/data/ru-fr_interference/2/wav_et_text...
45190,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,w,1.88000,0.04000,1.92000,/content/data/ru-fr_interference/2/wav_et_text...
45191,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,a,1.92000,0.06000,1.98000,/content/data/ru-fr_interference/2/wav_et_text...

In [54]:
meta = pd.read_csv(META_PATH, sep=";")
meta = meta.rename(columns={
    "spk": "speaker_id",
    "Gender": "gender",
    "Age": "age"
})
df = df.merge(meta[["speaker_id", "gender", "age"]], on="speaker_id", how="left")

In [55]:
df

,speaker_id,sentence_id,repetition,filename,lang,L1,label,onset,duration,offset,wav_path,gender,age
0,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,d,0.45231,0.10769,0.56000,/content/data/ru-fr_interference/2/wav_et_text...,f,22
1,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,i,0.56000,0.18000,0.74000,/content/data/ru-fr_interference/2/wav_et_text...,f,22
2,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,s,0.74000,0.14000,0.88000,/content/data/ru-fr_interference/2/wav_et_text...,f,22
3,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,e,0.88000,0.12142,1.00142,/content/data/ru-fr_interference/2/wav_et_text...,f,22
4,AB,FRcorp69,1,ab_rus_list1_FRcorp69,rus,L2,ʁ,1.00142,0.07858,1.08000,/content/data/ru-fr_interference/2/wav_et_text...,f,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45187,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,w,1.67000,0.03000,1.70000,/content/data/ru-fr_interference/2/wav_et_text...,m,23
45188,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,a,1.70000,0.06000,1.76000,/content/data/ru-fr_interference/2/wav_et_text...,m,23
45189,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,f,1.76000,0.12000,1.88000,/content/data/ru-fr_interference/2/wav_et_text...,m,23
45190,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,w,1.88000,0.04000,1.92000,/content/data/ru-fr_interference/2/wav_et_text...,m,23
45191,CB,FRcorp60,1,cb_fra_list1_FRcorp60,fra,L1,a,1.92000,0.06000,1.98000,/content/data/ru-fr_interference/2/wav_et_text...,m,23

In [23]:
df.to_csv(OUTPUT_PATH, index=False)